// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMqwF2uJ3vg8jya_LzKlGpNekGdTcG79s',
    appId: '1:636399033551:web:8cf3869416a5c1b674ebba',
    messagingSenderId: '636399033551',
    projectId: 'flutter-e-commerce-d4e98',
    authDomain: 'flutter-e-commerce-d4e98.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-d4e98.appspot.com',
    measurementId: 'G-QTPJCNT502',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigTg17phbsIeC9tOGdQ904CccWqSUZtw',
    appId: '1:636399033551:android:e6fecc3be7abd0f774ebba',
    messagingSenderId: '636399033551',
    projectId: 'flutter-e-commerce-d4e98',
    storageBucket: 'flutter-e-commerce-d4e98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_WM9g89vkjEZNjTl9_3Ns74H3mC7t90',
    appId: '1:636399033551:ios:b4798c2820ba6d0174ebba',
    messagingSenderId: '636399033551',
    projectId: 'flutter-e-commerce-d4e98',
    storageBucket: 'flutter-e-commerce-d4e98.appspot.com',
    androidClientId: '636399033551-6kj406efa18mmkim9dk3ddvo1ijk93s9.apps.googleusercontent.com',
    iosClientId: '636399033551-0dd23coufihuj7pu8heh0i3of912qbru.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE_WM9g89vkjEZNjTl9_3Ns74H3mC7t90',
    appId: '1:636399033551:ios:b4798c2820ba6d0174ebba',
    messagingSenderId: '636399033551',
    projectId: 'flutter-e-commerce-d4e98',
    storageBucket: 'flutter-e-commerce-d4e98.appspot.com',
    androidClientId: '636399033551-6kj406efa18mmkim9dk3ddvo1ijk93s9.apps.googleusercontent.com',
    iosClientId: '636399033551-0dd23coufihuj7pu8heh0i3of912qbru.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMqwF2uJ3vg8jya_LzKlGpNekGdTcG79s',
    appId: '1:636399033551:web:1ce0a9fed4661a8b74ebba',
    messagingSenderId: '636399033551',
    projectId: 'flutter-e-commerce-d4e98',
    authDomain: 'flutter-e-commerce-d4e98.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-d4e98.appspot.com',
    measurementId: 'G-Z08QE42D4M',
  );

}